// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbC1SzDSFaiocLXljniKuMBzwW57HpHCg',
    appId: '1:761057982117:web:fa332da687dc146407bf4c',
    messagingSenderId: '761057982117',
    projectId: 'presence-da92c',
    authDomain: 'presence-da92c.firebaseapp.com',
    storageBucket: 'presence-da92c.appspot.com',
    measurementId: 'G-TFL6G83L0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXQ9Vr8vmgqoKMCoItL_IuSwEiwSb4nGk',
    appId: '1:761057982117:android:6a8e4fd28fd83c9d07bf4c',
    messagingSenderId: '761057982117',
    projectId: 'presence-da92c',
    storageBucket: 'presence-da92c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXhPNX5y-3BsSxVQ4sdp1y-5ocJtST64E',
    appId: '1:761057982117:ios:1f9de8788e9175cd07bf4c',
    messagingSenderId: '761057982117',
    projectId: 'presence-da92c',
    storageBucket: 'presence-da92c.appspot.com',
    iosClientId: '761057982117-hdj2pqt5akm2at3um6h4189p3jtllhco.apps.googleusercontent.com',
    iosBundleId: 'com.bakti.presence.presence',
  );
}
